
# image build base
FROM debian

MAINTAINER hhuang <hhuang@student.42.fr>

ENV USER=hhuang
ENV HOSTNAME=42born2code

RUN echo "export PS1=\"$USER@\$HOSTNAME:/# \"" >> /root/.bashrc

CMD [ "/bin/bash" ]