## Configuration Apache
web:
   restart: always
   image: eboraas/apache-php
   ports:
      - "80:80"
   volumes:
      - /var/www:/var/www
      - /var/www/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
      - /var/www/docker/conf/apache/sites:/etc/apache2/sites-enabled
   environment:
      - ALLOW_OVERRIDE=true
   links:
      - db:db
      - phpmyadmin:phpmyadmin

db:
   image: mysql
   restart: always
   volumes:
    - /var/lib/boot2docker/mysql:/var/lib/mysql
   environment:
    - MYSQL_ROOT_PASSWORD=root

phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always
   ports:
    - "8080:80"
   links:
    - db:db